### ISSUE TITLE
Not allowed to pull docker file

### ISSUE THREAD

**Issue by KaffDaddy** [garvinhicking/demo-typo3-documentation-browsersync#1]
Executing the bash file or the command to run the docker container ends in

`docker run --rm -it --pull always \                                                            1 ✘  17:09:41 
         -v "./Documentation:/project/Documentation" \
         -v "./Documentation-GENERATED-temp:/project/Documentation-GENERATED-temp" \
         -p 5173:5173 ghcr.io/garvinhicking/typo3-documentation-browsersync:latest
docker: Error response from daemon: Head "https://ghcr.io/v2/garvinhicking/typo3-documentation-browsersync/manifests/latest": unauthorized.
See 'docker run --help'.`

**Comment by garvinhicking** [comment]
Hhhhhmmm. I thought it would be public by default. My first own docker container in the registry. Will need to look what I can do about it. ☹️

**Comment by garvinhicking** [comment]
Well, seems as if I create a private package, doh. Changed it to public, would you try again?

**Comment by KaffDaddy** [comment]
Great. Now it works perfectly smooth. I can make changes to the demo files and see it instantly in my browser.

**Comment by garvinhicking** [comment]
Phew that's great. Calling the URI unauthenticated in my iOS browser still shows missing auth, so I was afraid it wouldn't fix it.

But guess you generally need a docker auth to even access a public package.

Learning a lot here :-)
